# Generated by Django 6.0.3 on 2026-03-25 13:22

import colorfield.fields
import core.fields
import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_key', models.TextField()),
                ('passphrase', core.fields.EncryptedCharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('color', colorfield.fields.ColorField(default='#aaaaaa', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('script', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.CharField(db_index=True, max_length=255, verbose_name='object pk')),
                ('object_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='object id')),
                ('object_repr', models.TextField(verbose_name='object representation')),
                ('serialized_data', models.JSONField(null=True)),
                ('changes_text', models.TextField(blank=True, verbose_name='change message')),
                ('changes', models.JSONField(null=True, verbose_name='change message')),
                ('cid', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Correlation ID')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='remote address')),
                ('remote_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='remote port')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='additional data')),
                ('actor_email', models.CharField(blank=True, max_length=254, null=True, verbose_name='actor email')),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'create'), (1, 'update'), (2, 'delete'), (3, 'access'), (4, 'connect'), (5, 'disconnect'), (6, 'snippet run')], db_index=True, verbose_name='action')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'log entry',
                'verbose_name_plural': 'log entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('host', models.CharField(max_length=255, validators=[core.models.validate_host])),
                ('port', models.PositiveSmallIntegerField(blank=True, default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', core.fields.EncryptedCharField(blank=True, max_length=255)),
                ('icon', models.CharField(choices=[('linux', 'Linux'), ('ubuntu', 'Ubuntu'), ('debian', 'Debian'), ('alpine', 'Alpine'), ('redhat', 'Red Hat'), ('windows', 'Windows')], default='linux', max_length=20)),
                ('client_keys', models.ManyToManyField(blank=True, to='core.clientkey')),
                ('proxy_jump', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_jump_hosts', to='core.host')),
                ('tags', models.ManyToManyField(blank=True, to='core.hosttag')),
            ],
        ),
        migrations.CreateModel(
            name='SnippetExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('output', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.UUIDField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.host')),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.snippet')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
